// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskMaster.Domain;

namespace TaskMaster.Domain.Migrations
{
    [DbContext(typeof(TaskMasterContext))]
    [Migration("20201213193313_ProjectFieldsAdded")]
    partial class ProjectFieldsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TaskMaster.Domain.Models.ActionItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ActionItem");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.Comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProjectID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.ProjectState", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ProjectState");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.ActionItem", b =>
                {
                    b.HasOne("TaskMaster.Domain.Models.Project", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.Comment", b =>
                {
                    b.HasOne("TaskMaster.Domain.Models.Project", null)
                        .WithMany("Comments")
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.Project", b =>
                {
                    b.HasOne("TaskMaster.Domain.Models.ProjectState", "State")
                        .WithMany()
                        .HasForeignKey("StateID");

                    b.Navigation("State");
                });

            modelBuilder.Entity("TaskMaster.Domain.Models.Project", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
